import { recipeCardContent } from "../../Recipe-Card/recipeCardContent"

export const recipePageContent = {
  zuppaPiselli: {
    heroBg: {
      backgroundImage: `linear-gradient(rgba(0, 0, 0, 0.5),rgba(0, 0, 0, 0.3)), url(${recipeCardContent.zuppaDiPiselli.img})`,
    },
    recipeTitle: `${recipeCardContent.zuppaDiPiselli.label}`,
    recipeDescription: <><b>La zuppa di piselli</b> è un piatto avvolgente e nutriente da gustare nelle sere di primavera. Si prepara in poco tempo con <b><span style={{color: '#ae150d'}}>piselli freschi</span></b>, dolci e croccanti, oppure surgelati per tutte le stagioni.</>,
    ingredienti: [
      <>- 1 kg <span style={{color: '#3d5926'}}><b><u>Piselli</u></b></span></>,
      <>- 20 g <span style={{color: '#3d5926'}}><b><u>Panna fresca liquida</u></b></span></>,
      <>- 100 g <span style={{color: '#3d5926'}}><u><b>Cipolle bianche</b></u></span></>,
      <>- 30 g <span style={{color: '#3d5926'}}><u><b>Olio Extravergine d’oliva</b></u></span></>,
      <>- 50 g <span style={{color: '#3d5926'}}><u><b>Grana Padano DOP</b></u></span></>,
      <>- 100 g <span style={{color: '#3d5926'}}><u><b>Brodo vegetale</b></u></span></>,
      <>- <span style={{color: '#3d5926'}}><u><b>Sale fino</b> q.b</u></span></>,
      <>- <span style={{color: '#3d5926'}}><u><b>Pepe nero</b> q.b</u></span></>,
    ],
    steps: [
        <>In un tegame fate <b>scaldare l'olio leggermente a fuoco basso</b> e tuffate la cipolla.</>,
        <>Lasciate appassire leggermente la cipolla a <b>fuoco basso mescolando spesso</b> per evitare che si bruci. Dopodichè unite i piselli <i>(che usiate piselli freschi o congelati il procedimento sarà lo stesso)</i>. </>,
        <>Salate, pepate e mescolate il tutto.</>,
        <>Lasciate <b>cuocere circa 5 minuti</b>, poi coprite con 350g di brodo vegetale <i>(tenetene da parte 50g)</i>.</>,
        <>Continuate la cottura per <b>altri 15-20 minuti</b>, dopodichè spegnete il fuoco e usando un mixer ad immersione.</>,
        <><b>Frullate il tutto</b> aggiungendo man a mano il brodo vegetale tenuto da parte fino a raggiungere una <i>consistenza liscia e la densità desiderata</i>.</>,
        <>Aggiungete la <b>panna fresca</b>.</>,
        <>Riaccendete il fuoco e proseguite la cottura per <b>altri 5 minuti</b>, mescolando spesso.</>,
        <><b>Trasferite</b> la crema di piselli in un colino e <b>setacciatela</b> aiutandovi con una spatola per renderla più cremosa.</>,
        <><b>Impiattate</b> la vellutata e guarnitela con <b>scaglie di Grana Padano</b> a piacere prima di servirla calda o tiepida!</>
    ],
    dishType: `${recipeCardContent.zuppaDiPiselli.dishType}`,
    prepTime: `${recipeCardContent.zuppaDiPiselli.prepTime}`,
    difficulty: `${recipeCardContent.zuppaDiPiselli.difficulty}`,
    portions: `${recipeCardContent.zuppaDiPiselli.portions}`,
    addInfoImg: `${recipeCardContent.zuppaDiPiselli.img}`,
    addInfoImgAltText: `${recipeCardContent.zuppaDiPiselli.alt}`,
  },

  pastaAlPomodoro: {
    heroBg: {
      backgroundImage: `linear-gradient(rgba(0, 0, 0, 0.5),rgba(0, 0, 0, 0.3)), url(${recipeCardContent.pastaAlPomodoro.img})`,
    },
    recipeTitle: `${recipeCardContent.pastaAlPomodoro.label}`,
    recipeDescription: <> La <b>pasta al pomodoro e basilico</b> è una ricetta facile e sempre gradita da tutti. <b><span style={{color: '#ae150d'}}>Il sugo di pomodoro</span></b> ha molte varianti: si può preparare il sugo con pomodori freschi, oppure con la polpa, i pelati o la passata. I tempi di cottura cambiano in base alla scelta, ma di sicuro non cambia la bontà di questo primo piatto. </>,
    ingredienti: [
        <>- 187.5 g <span style={{color: '#3d5926'}}><u><b>Pasta</b></u></span></>,
        <>- 250 g <span style={{color: '#3d5926'}}><u><b>Polpa di pomodoro</b></u></span></>,
        <>- 1 <span style={{color: '#3d5926'}}><u><b>Spicchio d'aglio</b></u></span></>,
        <>- <span style={{color: '#3d5926'}}><u><b>Olio extravergine d’oliva</b></u></span></>,
        <>- <span style={{color: '#3d5926'}}><u><b>Basilico</b></u></span></>,
        <>- <span style={{color: '#3d5926'}}><u><b>Sale</b> q.b</u></span></>,
    ],
    steps: [
      <>Fate insaporire il sugo per qualche minuto a <b>fuoco vivace</b>.</>,
      <><b>Copritelo con un coperchio</b>, abbassate il calore e lasciatelo cuocere per circa <b>20 minuti</b>.</>,
      <>A fine cottura aggiungete le <b>foglie di basilico fresco</b>.</>,
      <>Cuocete il tipo di pasta che più preferite e <b>scolatela al dente</b> direttamente nel <b>sugo</b>.</>,
      <>Mescolate a fiamma viva per amalgamare bene e servite la <b>pasta al pomodoro con il basilico fresco</b>.</>
    ],
    dishType: `${recipeCardContent.pastaAlPomodoro.dishType}`,
    prepTime: `${recipeCardContent.pastaAlPomodoro.prepTime}`,
    difficulty: `${recipeCardContent.pastaAlPomodoro.difficulty}`,
    portions: `${recipeCardContent.pastaAlPomodoro.portions}`,
    addInfoImg: `${recipeCardContent.pastaAlPomodoro.img}`,
    addInfoImgAltText: `${recipeCardContent.pastaAlPomodoro.alt}`,
  },
  risoZafferano: {
    heroBg: {
      backgroundImage: `linear-gradient(rgba(0, 0, 0, 0.5),rgba(0, 0, 0, 0.3)), url(${recipeCardContent.risoZafferano.img})`,
    },
    recipeTitle: `${recipeCardContent.risoZafferano.label}`,
    recipeDescription: <> Il <b>risotto allo zafferano</b> è un classico primo piatto della cucina italiana, e si prepara con pochissimi ingredienti. Il bello di questo piatto è che per prepararlo per quattro persone basterà usare <b><span style={{color: '#ae150d'}}>una bustina di zafferano</span></b>, quindi per quanto sia un ingrediente costoso ne basterà pochissimo per portare in tavola un primo saporito! </>,
    ingredienti: [
        <>- 320 g <span style={{color: '#3d5926'}}><u><b>Riso per risotti</b></u></span></>,
        <>- 30 g <span style={{color: '#3d5926'}}><u><b>Burro</b></u></span></>,
        <>- 30 ml <span style={{color: '#3d5926'}}><u><b>Olio d'oliva</b></u></span></>,
        <>- 1 <span style={{color: '#3d5926'}}><u><b>Cipolla</b></u></span></>,
        <>- 1 bustina di <span style={{color: '#3d5926'}}><u><b>Zafferano</b></u></span></>,
        <>- 1 L <span style={{color: '#3d5926'}}><u><b>Brodo vegetale</b></u></span></>,
        <>- <span style={{color: '#3d5926'}}><u><b>Sale fino q.b</b></u></span></>,
        <> (Per mantecare): </>,
        <>- 40 g <span style={{color: '#3d5926'}}><u><b>Burro</b></u></span></>,
        <>- 40 g <span style={{color: '#3d5926'}}><u><b>Formaggio grattuggiato</b></u></span></>,
    ],
    steps: [
      <>Mettiamo in un tegame il <b>burro</b>, <b>l’olio di oliva</b> e <b>il sale </b>e facciamo scaldare.</>,
      <>Aggiungiamo la <b>cipolla</b> a pezzettini e facciamola soffriggere e stufare per circa <b>10 minuti mescolando spesso</b>.</>,
      <>Uniamo il riso e facciamolo <b>tostare per 2-3 minuti</b> mescolando con un cucchiaio di legno.</>,
      <>Aggiungiamo, poco per volta, il <b>brodo vegetale</b> caldo e portiamo a cottura il riso: ci vorranno circa <b>20 minuti</b>.</>,
      <>Dopo <b>5 minuti</b> circa possiamo aggiungere lo <b>zafferano</b>. Per comodità <span style={{color: '#ae150d'}}><i>consigliamo di metterlo in una ciotolina</i></span> e diluirlo con un po’ di brodo vegetale (preso dal totale).</>,
      <>Versiamo tutto lo zafferano nella pentola e, mescolando, continuiamo ad aggiungere il brodo fino a <b>portare a cottura il riso</b>.</>,
      <><span style={{color: '#ae150d'}}>A fine cottura</span> mantechiamo con il <b>burro e il formaggio grattugiato</b>, mescolando energicamente (assaggiamo il riso e, se occorre, aggiustiamo di sale).</>,
      <> Dividiamo il <b>risotto allo zafferano</b> nei piatti e serviamolo bello caldo.</>,
    ],
    
    dishType: `${recipeCardContent.risoZafferano.dishType}`,
    prepTime: `${recipeCardContent.risoZafferano.prepTime}`,
    difficulty: `${recipeCardContent.risoZafferano.difficulty}`,
    portions: `${recipeCardContent.risoZafferano.portions}`,
    addInfoImg: `${recipeCardContent.risoZafferano.img}`,
    addInfoImgAltText: `${recipeCardContent.risoZafferano.alt}`,
  },
  pastaFunghiPanna: {
    heroBg: {
      backgroundImage: `linear-gradient(rgba(0, 0, 0, 0.5),rgba(0, 0, 0, 0.3)), url(${recipeCardContent.pastaFunghiPanna.img})`,
    },
    recipeTitle: `${recipeCardContent.pastaFunghiPanna.label}`,
    recipeDescription: <> Le <b>pennette funghi e panna</b> sono un primo piatto vegetariano molto semplice da preparare. Per la preparazione possiamo utilizzare sia la panna vaccina, quella vegetale o di soia. Il piatto si prepara in poco tempo ed è considerabile un “salva cena”.</>,
    ingredienti: [
        <>- 250 g  <span style={{color: '#3d5926'}}><u><b>Funghi champignon a fettine</b></u></span></>,
        <>- 150 ml  <span style={{color: '#3d5926'}}><u><b>Panna vegetale</b></u></span></>,
        <>- <span style={{color: '#3d5926'}}><u><b>Sale fino q.b.</b></u></span></>,
        <>- 1 <span style={{color: '#3d5926'}}><u><b>Spicchio d'aglio</b></u></span></>,
        <>- 150 g <span style={{color: '#3d5926'}}><u><b>Pasta a piacere</b></u></span></>,
        <>- <span style={{color: '#3d5926'}}><u><b>Olio d'oliva q.b.</b></u></span></>,
        <>- 30 g <span style={{color: '#3d5926'}}><u><b>Formaggio grattugiato</b></u></span></>,
    ],
    steps: [
      <>In una padella cuociamo i <b>funghi champignon a fettine</b> con un filo <b>d’olio d’oliva</b>, <b>sale</b> e uno <b>spicchio d’aglio</b>. Nel frattempo mettiamo l’acqua per la pasta a bollire, uniamo anche il sale.</>,
      <>Quando i funghi saranno ben appassiti e cotti aggiungiamo la <b>panna</b>.</>,
      <>Mescoliamo bene, <i>non occorre aggiungere l’acqua perchè i funghi la rilasciano durante la cottura</i>.</>,
      <>Uniamo anche <b>2-3 cucchiai di formaggio grattugiato</b> e mescoliamo bene.</>,
      <>Buttiamo la pasta e cuociamola leggermente al dente.</>,
      <>Scoliamo la pasta e <b>uniamola al condimento</b>. Mescoliamo bene e la pasta sarà pronta per essere servita. Se lo avete si può aggiungere del <i>prezzemolo fresco tritato!</i></>,
    ],

    dishType: `${recipeCardContent.pastaFunghiPanna.dishType}`,
    prepTime: `${recipeCardContent.pastaFunghiPanna.prepTime}`,
    difficulty: `${recipeCardContent.pastaFunghiPanna.difficulty}`,
    portions: `${recipeCardContent.pastaFunghiPanna.portions}`,
    addInfoImg: `${recipeCardContent.pastaFunghiPanna.img}`,
    addInfoImgAltText: `${recipeCardContent.pastaFunghiPanna.alt}`,
  },
  bocconciniPolloAlLimone: {
    heroBg: {
      backgroundImage: `linear-gradient(rgba(0, 0, 0, 0.5),rgba(0, 0, 0, 0.3)), url(${recipeCardContent.bocconciniPolloAlLimone.img})`,
    },
    recipeTitle: `${recipeCardContent.bocconciniPolloAlLimone.label}`,
    recipeDescription: <> <b>I bocconcini di petto di pollo al limone</b> sono un secondo piatto facile che si prepara in poco tempo. Un’idea perfetta per chi è sempre di corsa.  <span style={{color: '#3d5926'}}><i>Il succo di limone con la farina</i></span> creerà una salsa gustosa, perfetta per fare scarpetta.
    Insieme al <b>tacchino</b> e al <b>coniglio</b>, il pollo fa parte del gruppo delle <b>carni bianche</b>, chiamate così perché caratterizzate da scarsa concentrazione di mioglobina, pigmento responsabile della colorazione delle carni.</>,
    ingredienti: [
        <>- 625 g  <span style={{color: '#3d5926'}}><u><b>Bocconcini di pollo</b></u></span></>,
        <>- 125 g  <span style={{color: '#3d5926'}}><u><b>Farina 00</b></u></span></>,
        <>- 3/4 <span style={{color: '#3d5926'}}><u><b>Cipolle</b></u></span></>,
        <>- 1,25 <span style={{color: '#3d5926'}}><u><b>Limoni</b></u> <i>(succo e scorza grattugiata)</i></span></>,
        <>- 250 ml <span style={{color: '#3d5926'}}><u><b>Acqua</b></u></span></>,
        <>- <span style={{color: '#3d5926'}}><u><b>Olio extravergine di oliva q.b.</b></u></span></>,
        <>- <span style={{color: '#3d5926'}}><u><b>Sale fino q.b.</b></u></span></>,
        <>- <span style={{color: '#3d5926'}}><u><b>Prezzemolo fresco fino q.b.</b></u></span></>,
    ],
    steps: [
      <> Mettiamo in una ciotola i <b>bocconcini di pollo</b> e aggiungiamo la <b>farina</b>, infarinandoli bene.</>,
      <>In una padella versiamo <b>dell’olio extravergine d’oliva</b> e tritiamo <b>mezza cipolla</b>. Aggiungiamo la <b>scorza grattugiata di un limone</b> e facciamo imbiondire la cipolla con la scorza del limone per qualche minuto.</>,
      <>Aggiungiamo poi i bocconcini di pollo infarinati e lasciamoli cuocere per qualche minuto, <i>girandoli per farli cuocere da tutti i lati</i>.</>,
      <>Versiamo il <b>succo del limone</b>, un po’ di sale e un bicchiere di acqua. Lasciamo cuocere i bocconcini di pollo al limone con il coperchio, girando ogni tanto per <b>circa 8 minuti</b>, se serve aggiungiamo ancora un po’ d’acqua.</>,
      <><span style={{color: '#ae150d'}}><b>Una volta cotti</b></span> mettiamo i bocconcini su un vassoio e aggiungiamo del <b>prezzemolo fresco tritato</b> in superficie. Portiamo in tavola i bocconcini cremosi, magari accompagnati con insalata e pomodori.</>,
    ],

    dishType: `${recipeCardContent.bocconciniPolloAlLimone.dishType}`,
    prepTime: `${recipeCardContent.bocconciniPolloAlLimone.prepTime}`,
    difficulty: `${recipeCardContent.bocconciniPolloAlLimone.difficulty}`,
    portions: `${recipeCardContent.bocconciniPolloAlLimone.portions}`,
    addInfoImg: `${recipeCardContent.bocconciniPolloAlLimone.img}`,
    addInfoImgAltText: `${recipeCardContent.bocconciniPolloAlLimone.alt}`,
  },
  involtiniDiZucchine: {
    heroBg: {
      backgroundImage: `linear-gradient(rgba(0, 0, 0, 0.5),rgba(0, 0, 0, 0.3)), url(${recipeCardContent.involtiniDiZucchine.img})`,
    },
    recipeTitle: `${recipeCardContent.involtiniDiZucchine.label}`,
    recipeDescription: <> La ricetta degli <b>involtini di zucchine al forno</b>, facile e veloce da realizzare, è un piatto sfizioso che richiede pochissimi ingredienti. Questi involtini si prestano per essere serviti come antipasto: si preparano con <i>zucchine grigliate e poi si farciscono con prosciutto crudo e formaggio</i>.</>,
    ingredienti: [
        <>- 2  <span style={{color: '#3d5926'}}><u><b>Zucchine medie</b></u></span></>,
        <>- 100 g  <span style={{color: '#3d5926'}}><u><b>Prosciutto crudo</b></u></span></>,
        <>- 80 g <span style={{color: '#3d5926'}}><u><b>Emmental senza lattosio</b></u> <i> (o Edamer) </i></span></>,
        <>- 1 <span style={{color: '#3d5926'}}><u><b>Uova</b></u><i> (per panare) </i></span></>,
        <>- <span style={{color: '#3d5926'}}><u><b>Pangrattato</b></u><i> (per panare - senza glutine per chi è intollerante) </i></span></>,
        <>- <span style={{color: '#3d5926'}}><u><b>Olio extravergine di oliva q.b.</b></u></span></>,
        <>- <span style={{color: '#3d5926'}}><u><b>Sale fino q.b.</b></u></span></>,
    ],

    steps: [
      <> Tagliamo <b>le zucchine</b> a strisce sottili e grigliamole.</>,
      <>Farciamo le zucchine con il <b>formaggio</b> e il <b>prosciutto</b>.</>,
      <>Arrotoliamo per formare l’involtino. Continuiamo fino a finire tutte le fette di zucchine.</>,
      <>Una volta pronti tutti gli involtini passiamoli <b>nell’uovo sbattuto</b>.</>,
      <>Passiamoli anche nel <b>pangrattato</b> senza glutine e chiudiamli con uno stuzzicadenti.</>,
      <>Mettiamo gli involtini in una <span style={{color: '#ae150d'}}><b>teglia da forno</b></span> e aggiungiamo <b>l’olio extravergine d’oliva</b>. Cuociamo in forno statico preriscaldato a <b>200 °C per 25 minuti circa</b>.</>,
      <>Potete servire gli involtini <i>appena sfornati o anche freddi il giorno dopo</i>.</>,
    ],

    dishType: `${recipeCardContent.involtiniDiZucchine.dishType}`,
    prepTime: `${recipeCardContent.involtiniDiZucchine.prepTime}`,
    difficulty: `${recipeCardContent.involtiniDiZucchine.difficulty}`,
    portions: `${recipeCardContent.involtiniDiZucchine.portions}`,
    addInfoImg: `${recipeCardContent.involtiniDiZucchine.img}`,
    addInfoImgAltText: `${recipeCardContent.involtiniDiZucchine.alt}`,
  },
}

